### PR TITLE
upgrade to md with external data

### PR DESCRIPTION
**Pull request by hosseinamin**
This upgrade removes almost all duplicate contents by allowing external contents as templates for each page and language.

New directory structure, In this upgrade templates of all front-matter based contents are stored at `.vuepress/frontmatter-templates`, And templates for md slots are stored at `.vuepress/content-templates`.

Inside these directories there is a base or common directory for the data that has repeatedly used in all pages. And the other sub directories are for language specific data.

- In `frontmatter-templates` you can find everything related to grid pages and layout of instructions pages.
- In `content-templates` you will find more language specific content, And it contains all duplicate slots used in the pages.

These external files are referenced on every page's front-matter specifically `external_templates_data` and `external_append_content`.

- `external_templates_data` should be a json object containing key as Its reference name inside the page and the value of it is relative path of the frontmatter-template.
- `external_append_content` is a list of all contents that will be added to the content of the md. Right now it contains mainly slots

I have leveraged the power of `copyof` method to reduce how much duplicate content will get generated. With copyof you can modify part of the frontmatter template data. For example in this file you can see the text size has reduced to fit in the box. `zu/speakbook/README.md#L133`.

```
  - name: page06
    copyof: grid_page06
    columns:
      0:
        rows:
          4:
            entries:
              5:
                comment: HOME
                inlinecss:
                  font-size: 14pt
          
      2:
        rows:
          2:
            entries:
              2:
                comment: I (Mina)
                inlinecss:
                  font-size: 18pt
 ```

Also there is a way to overwrite the existing data in the template (Like this). `ar/speakbook/README.md#L216`

```
    columns:
      0:
        rows:
          4:
            __OVERWRITE_rows:
              - image: shape-heart-1x-img
                text_key: i_love_you
              - image: shape-circle-1x-img
                text_key: yes
              - image: shape-triangle-1x-img
                text_key: no
              - image: shape-square-1x-img
                text_key: CAR

```

Let me know if you have any questions.

### CODE REVIEW

**Comment by willwade** [comment]
Thats a lot of work! Thankyou...

Will the scripts: apply-po-to-md.js , po-from-md.js po-google-translate all work still?

**Comment by hosseinamin** [comment]
@willwade I don't think so. That needs some work to get it going again.

**Comment by willwade** [comment]
> @willwade I don't think so. That needs some work to get it going again.

Ok - I can see those might need doing - but we can do that in a later PR. I'll just check all should look as it should :)

**Comment by willwade** [comment]
quick sanity check. All looks good. Note though - German - last page - Some missing letters.

**Comment by willwade** [comment]
@hosseinamin - that may have been because we did something bad. We might have hard written those letters in place rather than using the templated letters. Might just need to migrate those ones we have messed with like that.

**Comment by willwade** [comment]
Swedish colour version p7 (SPELL / STAVA page) not mirrored on this version - correct English version on left for comparison:
MicrosoftTeams-image (1)

**Comment by hosseinamin** [comment]
> Swedish colour version p7 (SPELL / STAVA page) not mirrored on this version - correct English version on left for comparison:
> MicrosoftTeams-image (1)

Okay. I see, There are few of these mistakes. I will fix it...

**Comment by hosseinamin** [comment]
@willwade I have added two commits to this PR. This should fix both issues you mentioned. Please confirm.

Thank you

**Pull request merged**
